POST 0.0.0.0:8080/admin/change_user_status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoiYWNjZXNzIn0.eyJ1c2VyX2lkIjo3NzcsImV4cCI6MTY2NzA1OTkzM30.EIsce0IMAe51T0Zye-xqtxQfM38XjY2jkvtbiKoexvQ

{
  "user_id": 555,
  "is_active": "True",
  "is_admin": "False"
}