POST 0.0.0.0:8080/admin/change_user_status
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoiYWNjZXNzIn0.eyJ1c2VyX2lkIjo3NzcsImV4cCI6MTY2NzE0NDc4Mn0.aCoiBzRuDITxiYnLD0Z0jA7K5ZslFGj-wTDRM5_Fb0U

{
  "user_id": 2,
  "is_active": "True",
  "is_admin": "True"
}