POST 0.0.0.0:8080/store/wallets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoiYWNjZXNzIn0.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjcxNDM1MjV9.z6yYJ3VDJAALToWHJhmRqIcXVV5WxERNoouxVNpFIlw