POST 0.0.0.0:8080/auth/refresh_token
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoicmVmcmVzaCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjcxNDYyMzV9.kT1qnxHAfqWc26RusX75-gGNMpMZyBVKEQ8J1zjeaak
