POST 0.0.0.0:8080/auth/refresh_token
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoicmVmcmVzaCJ9.eyJ1c2VyX2lkIjo3NzcsImV4cCI6MTY2NzQxMjc3NH0.YrW1Wdbtt-RiIaewXno2HyPpH8zBBSlP81mDca9sxGI
