
#POST 0.0.0.0:8080/auth/register
#Content-Type: application/json
#
#{
#  "login": "Davcevids",
#  "password": "132552"
#}

####

#GET http://0.0.0.0:8080/auth/activate/2
#Accept: application/json

###

POST 0.0.0.0:8080/auth/login
Content-Type: application/json

{"login": "admin", "password": "qwery123"}
