POST 0.0.0.0:8080/store/wallets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoicmVmcmVzaCJ9.eyJ1c2VyX2lkIjo1NTUsImV4cCI6MTY2Njk1NzU4MX0.peA__OSdO9qNO8K34KZRn0joJFB_slchGeFrPMNoqPc