POST 0.0.0.0:8080/store/wallets
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInR5cGUiOiJKV1QiLCJ0eXBlX3Rva2VuIjoiYWNjZXNzIn0.eyJ1c2VyX2lkIjo1NTUsImV4cCI6MTY2Njk0OTYyM30.-B3PjPFna4-Mx_dFP1Duq7WE_RU-YiH29f57BGoz0Bk